[package_management]
manager = "uv"

[ai]
rules = ""
mode = "manual"

[server]
follow_symlink = false
browser = "default"

[snippets]
include_default_snippets = true
custom_paths = []

[runtime]
default_sql_output = "auto"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
reactive_tests = true
auto_reload = "off"
watcher_on_save = "lazy"
auto_instantiate = true

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false

[completion]
copilot = false
activate_on_typing = true

[keymap]
preset = "default"

[keymap.overrides]

[experimental]

[display]
code_editor_font_size = 14
cell_output = "above"
dataframes = "rich"
theme = "light"
default_table_page_size = 10
default_width = "medium"

[formatting]
line_length = 79

[language_servers.pylsp]
enable_ruff = true
enable_pylint = false
enable_pyflakes = false
enable_pydocstyle = false
enable_flake8 = false
enable_mypy = true
enabled = true
